CREATE TABLE TB_CLIENTES(
	CPF VARCHAR(11),
	NOME VARCHAR2(100),
	ENDERECO1 VARCHAR2(150),
	ENDERECO2 VARCHAR2(150),
	BAIRRO VARCHAR2(50),
	CIDADE VARCHAR(50),
	ESTADO VARCHAR(2),
	CEP VARCHAR2(8),
	IDADE INT,
	SEXO VARCHAR2(2),
	LIMITE_CREDITO FLOAT,
	VOLUME_COMPRA FLOAT,
	PRIMEIRA_COMPRA NUMBER(1))