UPDATE TB_PRODUTOS SET SABOR = 'Cítricos' WHERE PRODUTO = '1088126';
UPDATE TB_PRODUTOS SET SABOR = 'Cítricos' WHERE PRODUTO = '544931';
UPDATE TB_PRODUTOS SET SABOR = 'Cítricos' WHERE PRODUTO = '544931';
